# Generated by Django 5.2.13 on 2026-04-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_answer', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('valid_variants', models.JSONField(blank=True, default=list)),
                ('embedding_vector', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('cpp', 'C++'), ('python', 'Python'), ('java', 'Java'), ('french', 'Français')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('max_points', models.FloatField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
