# Generated by Django 5.2.13 on 2026-04-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='processing_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='reference_file',
            field=models.FileField(blank=True, null=True, upload_to='exams/references/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'Traitement OCR...'), ('done', 'Prêt'), ('error', 'Erreur')], default='done', max_length=20),
        ),
    ]
