# Generated by Django 5.2.13 on 2026-04-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_processing_log_exam_reference_file_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject_file',
            field=models.FileField(blank=True, null=True, upload_to='exams/subjects/'),
        ),
    ]
