# Generated by Django 5.2.14 on 2026-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_subject_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('cpp', 'C++')], default='cpp', max_length=50),
        ),
    ]
